

<h1>發表文章</h1>
<form method="post" action="<?php echo $this->url(array('controller'=>'article','action'=>'post'),NULL,true);?>">
    
    <p>文章標題 <input type="text" name="title" /></p>
    
    <p>發表時間 <input type="timestamp" name="date" value="<?php echo $this->time ?>"/></p> 
    
    <p>分類 <select name="category_id"> 
            <?php foreach($this->categories as $category) :  //讓它自動跑迴圈~讓分類選項和名字自己完成?>
            <option value="<?php echo $category->id;?>"><?php echo $category->name;?></option>
            <?php endforeach ?>
        </select></p>
    <p>是否置頂 <input type="radio" name="top" value="0" />是 
               <input type="radio" name="top" value="1" />否 </p>
    <p>內文<br/>
                <textarea name="text" row="100" cols="100"></textarea>
            </p> 
            <p><input type="submit" value="送出"/></p>
    
</form>
