<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user', 'category_id', 'integer', '4', array(
             'notblank' => '1',
             ));
        $this->addColumn('user', 'comment', 'string', '300', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('user', 'category_id');
        $this->removeColumn('user', 'comment');
    }
}