<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user', 'comment', 'string', '300', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('user', 'comment');
    }
}