<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('article', array(
             'id' => 
             array(
              'primary' => '1',
              'unsigned' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'title' => 
             array(
              'default' => '',
              'type' => 'string',
              'length' => '255',
             ),
             'text' => 
             array(
              'default' => '',
              'type' => 'string',
              'length' => '',
             ),
             'user_id' => 
             array(
              'unsigned' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('category', array(
             'id' => 
             array(
              'primary' => '1',
              'unsigned' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'name' => 
             array(
              'default' => '',
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('article');
        $this->dropTable('category');
    }
}