<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('article', 'article_user_id_user_id_1', array(
             'name' => 'article_user_id_user_id_1',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('article', 'article_category_id_category_id', array(
             'name' => 'article_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->addIndex('article', 'article_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('article', 'article_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('article', 'article_user_id_user_id_1');
        $this->dropForeignKey('article', 'article_category_id_category_id');
        $this->removeIndex('article', 'article_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('article', 'article_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
    }
}