<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('user', 'category_id');
    }

    public function down()
    {
        $this->addColumn('user', 'category_id', 'integer', '4', array(
             'notblank' => '1',
             ));
    }
}