<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<h1>User Sign On</h1>


<form method="post" action="<?php echo $this->url();?>">

    <p>請登入 </p>
    <p>使用者名稱 <input type="text" name="name" /></p>
    <p>密碼 <input type="password" name="password" /></p>
    

    <p><a href="<?php echo $this->url(array('controller'=>'article','action'=>'category','category_id'=>$article->category_id),NULL,true) ;?>"><input type="submit" value="登入" /></a></p>
</form>