<html>
    <title>陽春的 MVC 留言板</title>
    <body>

        <h1>歡迎觀看陽春留言板</h1>
        <a href="index.php?controller=guestbook&action=post">我要留言</a> ,
        <a href="index.php">回首頁</a>

        <?php foreach ($this->view->entries as $data): ?>

            <p>留言者姓名：<?php echo $data['name']; ?></p>
            <p>信箱：<?php echo $data['email']; ?></p>
            <p>內容：</p>
            <p><?php echo nl2br($data['text']); ?></p>
            <p>時間：<?php echo date('Y/m/d H:i', $data['datetime']); ?></p>


            <hr />  //分隔線


        <?php endforeach ?>

    </body>

</html>
