<html>
    <title>留言板的留言表單</title>
    <body>

        <h1>歡迎在陽春留言板留言</h1>
        <a href="index.php?controller=guestbook&action=index">回去看留言</a>

        <form method="post" action="index.php?controller=guestbook&action=post">

            <p>姓名：<input type="text" name="name"></p>
            <p>信箱：<input type="text" name="email" size="40"></p>
            <p>請填寫留言：<br />
                <textarea name="text" rows="10" cols="40"></textarea>
            </p>

            <p><input type="submit" name="submit" value="送出" /></p>


        </form>
    </body>
</html>

