<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh" lang="zh">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>

        <h1>Welcome Big Blog</h1>

        <div>

            <?php if( $this->logined == true ):?>
            觀迎回來
            
            <a href="<?php echo $this->url(array('action'=>'index','controller'=>'index'),NULL,true);?>">回到首頁</a>
            <a href="<?php echo $this->url(array('action' => 'post', 'controller' => 'blog'), NULL, true); ?>">登記blog</a>
            <a href="<?php echo $this->url(array('action'=>'post','controller'=>'article'),NULL,true);?>">我要發文</a>
            <a href="<?php echo $this->url(array('action'=>'get','controller'=>'blog','isMine'=>true),NULL,true);?>">我的Blog</a>
            <a href="<?php echo $this->url(array('action'=>'signout','controller'=>'user'),NULL,true);?>">我要登出</a>
            
            <?php else:?>
            <a href="<?php echo $this->url(array('action'=>'post','controller'=>'user'),NULL,true);?>">我要註冊</a>
            <a href="<?php echo $this->url(array('action'=>'sign','controller'=>'user'),NULL,true);?>">我要登入</a>
            <?php endif?>
        </div>

        <div>
            <?php echo $this->layout()->content ?>
        </div>

    </body>
</html>