<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcategory extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('category', array(
             'id' => 
             array(
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'type' => 'integer',
              'length' => 4,
             ),
             'name' => 
             array(
              'default' => '',
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('category');
    }
}