<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addarticle extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('article', array(
             'id' => 
             array(
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'type' => 'integer',
              'length' => 4,
             ),
             'title' => 
             array(
              'notblank' => true,
              'type' => 'string',
              'length' => 50,
             ),
             'date' => 
             array(
          
              'type' => 'timestamp',
              
             ),
             'user_id' => 
             array(
              'unsigned' => true,
              'default' => NULL,
              'type' => 'integer',
              'length' => 4,
             ),
             'category_id' => 
             array(
              'unsigned' => true,
              'default' => NULL,
              'type' => 'integer',
              'length' => 4,
             ),
             'text' => 
             array(
              'default' => '',
              'type' => 'string',
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('article');
    }
}