<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('article', 'article_blog_id_blog_id_1', array(
             'name' => 'article_blog_id_blog_id_1',
             'local' => 'blog_id',
             'foreign' => 'id',
             'foreignTable' => 'blog',
             ));
        $this->addIndex('article', 'article_blog_id', array(
             'fields' => 
             array(
              0 => 'blog_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('article', 'article_blog_id_blog_id_1');
        $this->removeIndex('article', 'article_blog_id', array(
             'fields' => 
             array(
              0 => 'blog_id',
             ),
             ));
    }
}