<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('article', 'article_user_id_user_id', array(
             'name' => 'article_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             'onUpdate' => NULL,
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('article', 'article_category_id_category_id', array(
             'name' => 'article_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             'onUpdate' => NULL,
             'onDelete' => 'SET NULL',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('article', 'article_user_id_user_id');
        $this->dropForeignKey('article', 'article_category_id_category_id');
    }
}